"""Generate attribution and OSS credit artifacts from structured sources."""

from __future__ import annotations

import json
from pathlib import Path
from typing import Any

import jsonschema

from mt_pipeline.publish import attribution as publish_attribution


DATA_BEGIN = "<!-- BEGIN GENERATED DATA SOURCES -->"
DATA_END = "<!-- END GENERATED DATA SOURCES -->"
OSS_BEGIN = "<!-- BEGIN GENERATED OSS CREDITS -->"
OSS_END = "<!-- END GENERATED OSS CREDITS -->"

APP_CATEGORIES = {"ios_app", "mirrored_asset"}
CATEGORY_TITLES = {
    "ios_app": "iOS App OSS",
    "mirrored_asset": "Mirrored Assets",
}
CATEGORY_ORDER = {
    "ios_app": 0,
    "mirrored_asset": 1,
}


def repo_root_from_module() -> Path:
    return Path(__file__).resolve().parents[4]


def load_json(path: Path) -> Any:
    return json.loads(path.read_text(encoding="utf-8"))


def load_a1d_sources(root: Path) -> dict[str, dict[str, Any]]:
    return _source_entries(load_json(root / "pipeline/config/a1d_sources.json"))


def load_oss_registry(root: Path) -> dict[str, Any]:
    registry = load_json(root / "contracts/oss-credits.json")
    schema = load_json(root / "contracts/schemas/oss-credits.schema.json")
    jsonschema.Draft202012Validator(
        schema,
        format_checker=jsonschema.Draft202012Validator.FORMAT_CHECKER,
    ).validate(registry)
    return registry


def replace_generated_section(
    original: str,
    begin_marker: str,
    end_marker: str,
    generated_body: str,
) -> str:
    if original.count(begin_marker) != 1:
        raise ValueError(f"expected exactly one marker: {begin_marker}")
    if original.count(end_marker) != 1:
        raise ValueError(f"expected exactly one marker: {end_marker}")

    begin_marker_index = original.index(begin_marker)
    end = original.index(end_marker)
    if begin_marker_index > end:
        raise ValueError(f"begin marker must precede end marker: {begin_marker}")

    begin = begin_marker_index + len(begin_marker)
    body = "\n" + generated_body.rstrip() + "\n"
    return original[:begin] + body + original[end:]


def render_data_sources_markdown(a1d_sources: dict[str, dict[str, Any]]) -> str:
    a1d_sources = _source_entries(a1d_sources)
    attrs = publish_attribution.attribution_for(
        set(a1d_sources),
        a1d_sources,
        includes_osm_basemap=True,
    )
    lines = [
        "<!-- Generated by scripts/generate_attribution.py. Do not edit by hand. -->",
        "",
        "| Source key | License | Manifest attribution text |",
        "|---|---|---|",
    ]
    for attr in attrs:
        lines.append(
            "| {source} | {license} | {text} |".format(
                source=_md_cell(attr["source"]),
                license=_md_cell(attr["license"]),
                text=_md_cell(attr["text"]),
            )
        )
    return "\n".join(lines)


def render_oss_markdown(registry: dict[str, Any]) -> str:
    lines = [
        "<!-- Generated by scripts/generate_attribution.py. Do not edit by hand. -->",
    ]
    for category, entries in _grouped_credits(registry):
        lines.extend(
            [
                "",
                f"### {CATEGORY_TITLES[category]}",
                "",
                "| Name | Version / pin | Evidence | License | Compliance |",
                "|---|---|---|---|---|",
            ]
        )
        for credit in entries:
            evidence = "<br>".join(f"`{_md_cell(item)}`" for item in credit["evidence"])
            license_text = "[{spdx}]({url})".format(
                spdx=_md_cell(credit["license_spdx"]),
                url=credit["license_url"],
            )
            lines.append(
                "| {name} | {pin} | {evidence} | {license} | {compliance} |".format(
                    name=_md_cell(credit["name"]),
                    pin=_md_cell(credit["version_or_pin"]),
                    evidence=evidence,
                    license=license_text,
                    compliance=_md_cell(credit["compliance"]),
                )
            )
    return "\n".join(lines)


def render_attribution_markdown(root: Path) -> str:
    path = root / "attribution.md"
    original = path.read_text(encoding="utf-8")
    updated = replace_generated_section(
        original,
        DATA_BEGIN,
        DATA_END,
        render_data_sources_markdown(load_a1d_sources(root)),
    )
    updated = replace_generated_section(
        updated,
        OSS_BEGIN,
        OSS_END,
        render_oss_markdown(load_oss_registry(root)),
    )
    return updated


def render_app_credits_json(registry: dict[str, Any], *, root: Path | None = None) -> str:
    root = root or repo_root_from_module()
    credits = [
        _app_credit(credit, root)
        for credit in sorted(registry["credits"], key=lambda item: item["name"].casefold())
        if credit["app_resource"]
    ]
    return json.dumps(
        {
            "schema_version": 1,
            "credits": credits,
        },
        indent=2,
        sort_keys=True,
    ) + "\n"


def expected_outputs(root: Path) -> dict[Path, str]:
    registry = load_oss_registry(root)
    return {
        root / "attribution.md": render_attribution_markdown(root),
        root / "ios/App/Sources/OSSCredits.json": render_app_credits_json(
            registry,
            root=root,
        ),
    }


def write_outputs(root: Path) -> None:
    for path, content in expected_outputs(root).items():
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content, encoding="utf-8")


def stale_outputs(root: Path) -> list[Path]:
    stale = []
    for path, content in expected_outputs(root).items():
        if not path.exists() or path.read_text(encoding="utf-8") != content:
            stale.append(path)
    return stale


def _grouped_credits(registry: dict[str, Any]) -> list[tuple[str, list[dict[str, Any]]]]:
    grouped: dict[str, list[dict[str, Any]]] = {}
    for credit in registry["credits"]:
        grouped.setdefault(credit["category"], []).append(credit)
    return [
        (category, sorted(entries, key=lambda item: item["name"].casefold()))
        for category, entries in sorted(
            grouped.items(),
            key=lambda item: CATEGORY_ORDER[item[0]],
        )
    ]


def _app_credit(credit: dict[str, Any], root: Path) -> dict[str, Any]:
    if credit["category"] not in APP_CATEGORIES:
        raise ValueError(f"non-app credit marked app_resource: {credit['name']}")
    notice_path = root / credit["notice_path"]
    return {
        "acknowledgement": (
            f"{credit['name']} ({credit['version_or_pin']}) is licensed under "
            f"{credit['license_spdx']}."
        ),
        "category": credit["category"],
        "license_spdx": credit["license_spdx"],
        "license_url": credit["license_url"],
        "name": credit["name"],
        "notice_text": notice_path.read_text(encoding="utf-8"),
        "version_or_pin": credit["version_or_pin"],
    }


def _md_cell(value: str) -> str:
    return str(value).replace("|", "\\|").replace("\n", " ")


def _source_entries(raw: dict[str, Any]) -> dict[str, dict[str, Any]]:
    return {
        key: value
        for key, value in raw.items()
        if isinstance(value, dict) and value.get("attribution")
    }
